@echo off
echo Navigating to project folder...
cd C:\Users\User\.gemini\antigravity\scratch\portfolio-react
echo Adding files to git...
git add .
echo Committing changes...
git commit -m "feat: complete WOW factor redesign and fixes"
echo Pulling latest changes from GitHub...
git pull origin main --no-rebase
echo Pushing to GitHub...
git push origin main
echo Done!
pause
